#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 26 09:33:01 2022

@author: amandamatos
"""

#%% Importanto bibliotecas
import pandas as pd
from datetime import datetime
from plotly.subplots import make_subplots
import plotly.graph_objects as go


#%% 
df_chuva = pd.read_csv('chuva.csv')
df_chuva['data'] = df_chuva['hordatahora'].astype(str).str[:10]
df_chuva = df_chuva.drop(['hordatahora'], axis = 1)

df_chuva = df_chuva.groupby(df_chuva['data']).sum()
df_chuva = df_chuva.reset_index()
df_chuva['data'] = df_chuva.apply(lambda x: datetime.strptime(x['data'], '%d/%m/%Y'), axis=1)
df_chuva = df_chuva.set_index(['data'])
df_chuva = df_chuva.sort_index(axis = 0)

df_media_chuva = df_chuva.mean(axis=1)
df_media_chuva = pd.DataFrame(df_media_chuva)
df_media_chuva.columns = ['media']


df_obs = pd.read_csv('uv_vazao.csv')
df_sim = pd.read_csv('uv_vazao_simulada.csv')


df_Q = pd.concat([df_obs, df_sim], axis = 1)
df_Q = df_Q.set_index(['datahora'])

#%% Plotando com plotly - subplots: chuva-vazao

fig = make_subplots(rows=3, cols=1, shared_xaxes=True, specs=[[{'rowspan': 1, 'colspan': 1}],[{'rowspan': 2, 'colspan': 1}],[{'rowspan': 0, 'colspan': 0}]])
fig.add_trace(go.Scatter(x=df_media_chuva.index, y=df_media_chuva['media'], name="PME (mm)"), row=1, col=1)
fig['layout']['yaxis']['autorange'] = "reversed"
fig.add_trace(go.Scatter(x=df_Q.index, y=df_Q['Observado'], name="Observado (m3/s)", marker_color='black'), row=2, col=1)
fig.add_trace(go.Scatter(x=df_Q.index, y=df_Q['Simulado02'], name="Simulado (m3/s)", marker_color='red'), row=2, col=1)
fig.update_yaxes(title_text='Chuva ', row=1, col=1)
fig.update_yaxes(title_text='Vazão ', row=2, col=1)
fig.update_layout(legend_title_text='Comparação Modelo SHETRAN')
fig.update_layout(autosize=False,width=1600,height=900,margin=dict(l=30,r=30,b=10,t=10))
fig.write_html('comparacao_shetran.html')
fig.show()